---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

> Los perretes y gatetes se hacen mayores en las protectoras, ¡ayúdemoslos!

Encuentra el gato o perro más mayor en adopción de la [protectora ANAA](http://www.anaaweb.org/)

Un script en [#rstats](https://twitter.com/hashtag/rstats), en honor al [script de Jenny Bryan](https://github.com/jennybc/fattest-cat) para encontrar los gatos más gordos en el [centro de adopción SF SPCA](https://www.sfspca.org/adoptions/cats)


## Instalar y uso del script

Shell

```
wget https://raw.githubusercontent.com/chucheria/oldest-pet/master/oldest-pet.R
chmod +x oldest-pet.R
./oldest-pet.R
```

R

```{r eval = FALSE}
url <- "https://raw.githubusercontent.com/chucheria/oldest-pet/master/oldest-pet.R"
rfile <- basename(url)
download.file(url, rfile)
source(rfile)
```

Elige entre **1** o **2** para buscar *gatos* o *perros*.

